export const USER_LOGGED_OUT = 'USER_LOGGED_OUT ';
export type USER_LOGGED_OUT = typeof USER_LOGGED_OUT;

export const USER_SIGN_IN = 'USER_SIGN_IN';
export type USER_SIGN_IN = typeof USER_SIGN_IN;

export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export type USER_SIGN_IN_SUCCESS = typeof USER_SIGN_IN_SUCCESS;

export const USER_SIGN_UP = 'USER_SIGN_UP';
export type USER_SIGN_UP = typeof USER_SIGN_UP;

export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export type USER_SIGN_UP_SUCCESS = typeof USER_SIGN_UP_SUCCESS;

export const USER_CONFIRM_EMAIL = 'USER_CONFIRM_EMAIL';
export type USER_CONFIRM_EMAIL = typeof USER_CONFIRM_EMAIL;

export const USER_CONFIRM_EMAIL_SUCCESS = 'USER_CONFIRM_EMAIL_SUCCESS';
export type USER_CONFIRM_EMAIL_SUCCESS = typeof USER_CONFIRM_EMAIL_SUCCESS;

export const SET_LOADING = 'SET_LOADING';
export type SET_LOADING = typeof SET_LOADING;

export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export type SET_AUTH_ERROR = typeof SET_AUTH_ERROR;

export const SET_SEARCH_ERROR = 'SET_SEARCH_ERROR';
export type SET_SEARCH_ERROR = typeof SET_SEARCH_ERROR;

export const USER_SUBMIT_EMAIL = 'USER_SUBMIT_EMAIL';
export type USER_SUBMIT_EMAIL = typeof USER_SUBMIT_EMAIL;

export const USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD';
export type USER_CHANGE_PASSWORD = typeof USER_CHANGE_PASSWORD;

export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE';
export type SET_SUCCESS_MESSAGE = typeof SET_SUCCESS_MESSAGE;

export const SET_LANGUAGE = 'SET_LANGUAGE';
export type SET_LANGUAGE = typeof SET_LANGUAGE;

export const SET_FILTER_RESULTS = 'SET_FILTER_RESULTS';
export type SET_FILTER_RESULTS = typeof SET_FILTER_RESULTS;

export const CLEAR_CAR_FILTERS = 'CLEAR_CAR_FILTERS';
export type CLEAR_CAR_FILTERS = typeof CLEAR_CAR_FILTERS;

export const SET_FILTER_VALUES = 'SET_FILTER_VALUES';
export type SET_FILTER_VALUES = typeof SET_FILTER_VALUES;

export const SET_CURRENT_FILTER = 'SET_CURRENT_FILTER';
export type SET_CURRENT_FILTER = typeof SET_CURRENT_FILTER;

export const FETCH_MARKS_VALUES = 'FETCH_MARKS_VALUES';
export type FETCH_MARKS_VALUES = typeof FETCH_MARKS_VALUES;

export const SET_MARKS_VALUES = 'SET_MARKS_VALUES';
export type SET_MARKS_VALUES = typeof SET_MARKS_VALUES;

export const FETCH_BODY_TYPES_VALUES = 'FETCH_BODY_TYPES_VALUES';
export type FETCH_BODY_TYPES_VALUES = typeof FETCH_BODY_TYPES_VALUES;

export const SET_BODY_TYPES_VALUES = 'SET_BODY_TYPES_VALUES';
export type SET_BODY_TYPES_VALUES = typeof SET_BODY_TYPES_VALUES;

export const FETCH_MODELS_VALUES = 'FETCH_MODELS_VALUES';
export type FETCH_MODELS_VALUES = typeof FETCH_MODELS_VALUES;

export const SET_MODELS_VALUES = 'SET_MODELS_VALUES';
export type SET_MODELS_VALUES = typeof SET_MODELS_VALUES;

export const SET_SORTING_PARAMS = 'SET_SORTING_PARAMS';
export type SET_SORTING_PARAMS = typeof SET_SORTING_PARAMS;

export const SET_ADS_AS_LOADED = 'SET_ADS_AS_LOADED';
export type SET_ADS_AS_LOADED = typeof SET_ADS_AS_LOADED;

export const FETCH_SAVED_FILTERS = 'FETCH_SAVED_FILTERS';
export type FETCH_SAVED_FILTERS = typeof FETCH_SAVED_FILTERS;

export const SET_SAVED_SEARCH_FILTERS = 'SET_SAVED_SEARCH_FILTERS';
export type SET_SAVED_SEARCH_FILTERS = typeof SET_SAVED_SEARCH_FILTERS;
