export const USER_LOGGED_OUT = 'USER_LOGGED_OUT ';
export type USER_LOGGED_OUT = typeof USER_LOGGED_OUT;

export const USER_SIGN_IN = 'USER_SIGN_IN';
export type USER_SIGN_IN = typeof USER_SIGN_IN;

export const SELECT_AD = 'SELECT_AD';
export type SELECT_AD = typeof SELECT_AD;

export const CLEAR_SELECTED_AD = 'CLEAR_SELECTED_AD';
export type CLEAR_SELECTED_AD = typeof CLEAR_SELECTED_AD;

export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export type USER_SIGN_IN_SUCCESS = typeof USER_SIGN_IN_SUCCESS;

export const USER_SIGN_UP = 'USER_SIGN_UP';
export type USER_SIGN_UP = typeof USER_SIGN_UP;

export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export type USER_SIGN_UP_SUCCESS = typeof USER_SIGN_UP_SUCCESS;

export const USER_CONFIRM_EMAIL = 'USER_CONFIRM_EMAIL';
export type USER_CONFIRM_EMAIL = typeof USER_CONFIRM_EMAIL;

export const USER_CONFIRM_EMAIL_SUCCESS = 'USER_CONFIRM_EMAIL_SUCCESS';
export type USER_CONFIRM_EMAIL_SUCCESS = typeof USER_CONFIRM_EMAIL_SUCCESS;

export const SET_LOADING = 'SET_LOADING';
export type SET_LOADING = typeof SET_LOADING;

export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export type SET_AUTH_ERROR = typeof SET_AUTH_ERROR;

export const SET_SEARCH_ERROR = 'SET_SEARCH_ERROR';
export type SET_SEARCH_ERROR = typeof SET_SEARCH_ERROR;

export const USER_SUBMIT_EMAIL = 'USER_SUBMIT_EMAIL';
export type USER_SUBMIT_EMAIL = typeof USER_SUBMIT_EMAIL;

export const USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD';
export type USER_CHANGE_PASSWORD = typeof USER_CHANGE_PASSWORD;

export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE';
export type SET_SUCCESS_MESSAGE = typeof SET_SUCCESS_MESSAGE;

export const SET_LANGUAGE = 'SET_LANGUAGE';
export type SET_LANGUAGE = typeof SET_LANGUAGE;

export const CHANGE_USER_DATA = 'CHANGE_USER_DATA';
export type CHANGE_USER_DATA = typeof CHANGE_USER_DATA;

export const CHANGE_USER_DATA_SUCCESS = 'CHANGE_USER_DATA_SUCCESS';
export type CHANGE_USER_DATA_SUCCESS = typeof CHANGE_USER_DATA_SUCCESS;

export const SET_CHANGE_USER_DATA_ERROR = 'SET_CHANGE_USER_DATA_ERROR';
export type SET_CHANGE_USER_DATA_ERROR = typeof SET_CHANGE_USER_DATA_ERROR;

export const CHANGE_USER_AVATAR = 'CHANGE_USER_AVATAR';
export type CHANGE_USER_AVATAR = typeof CHANGE_USER_AVATAR;

export const CHANGE_USER_SETTINGS = 'CHANGE_USER_SETTINGS';
export type CHANGE_USER_SETTINGS = typeof CHANGE_USER_SETTINGS;

export const SET_FILTER_RESULTS = 'SET_FILTER_RESULTS';
export type SET_FILTER_RESULTS = typeof SET_FILTER_RESULTS;

export const CLEAR_CAR_FILTERS = 'CLEAR_CAR_FILTERS';
export type CLEAR_CAR_FILTERS = typeof CLEAR_CAR_FILTERS;

export const SET_FILTER_VALUES = 'SET_FILTER_VALUES';
export type SET_FILTER_VALUES = typeof SET_FILTER_VALUES;

export const SET_CURRENT_FILTER = 'SET_CURRENT_FILTER';
export type SET_CURRENT_FILTER = typeof SET_CURRENT_FILTER;

export const FETCH_MARKS_VALUES = 'FETCH_MARKS_VALUES';
export type FETCH_MARKS_VALUES = typeof FETCH_MARKS_VALUES;

export const SET_MARKS_VALUES = 'SET_MARKS_VALUES';
export type SET_MARKS_VALUES = typeof SET_MARKS_VALUES;

export const FETCH_BODY_TYPES_VALUES = 'FETCH_BODY_TYPES_VALUES';
export type FETCH_BODY_TYPES_VALUES = typeof FETCH_BODY_TYPES_VALUES;

export const SET_BODY_TYPES_VALUES = 'SET_BODY_TYPES_VALUES';
export type SET_BODY_TYPES_VALUES = typeof SET_BODY_TYPES_VALUES;

export const FETCH_MODELS_VALUES = 'FETCH_MODELS_VALUES';
export type FETCH_MODELS_VALUES = typeof FETCH_MODELS_VALUES;

export const SET_MODELS_VALUES = 'SET_MODELS_VALUES';
export type SET_MODELS_VALUES = typeof SET_MODELS_VALUES;

export const SET_SORTING_PARAMS = 'SET_SORTING_PARAMS';
export type SET_SORTING_PARAMS = typeof SET_SORTING_PARAMS;

export const SET_ADS_AS_LOADED = 'SET_ADS_AS_LOADED';
export type SET_ADS_AS_LOADED = typeof SET_ADS_AS_LOADED;

export const FETCH_SAVED_FILTERS = 'FETCH_SAVED_FILTERS';
export type FETCH_SAVED_FILTERS = typeof FETCH_SAVED_FILTERS;

export const SUBMIT_SAVED_FILTERS = 'SUBMIT_SAVED_FILTERS';
export type SUBMIT_SAVED_FILTERS = typeof SUBMIT_SAVED_FILTERS;

export const SET_SAVED_SEARCH_FILTERS = 'SET_SAVED_SEARCH_FILTERS';
export type SET_SAVED_SEARCH_FILTERS = typeof SET_SAVED_SEARCH_FILTERS;

export const FETCH_SAVED_SEARCH_RESULTS = 'FETCH_SAVED_SEARCH_RESULTS';
export type FETCH_SAVED_SEARCH_RESULTS = typeof FETCH_SAVED_SEARCH_RESULTS;

export const SET_SAVED_SEARCH_RESULTS = 'SET_SAVED_SEARCH_RESULTS';
export type SET_SAVED_SEARCH_RESULTS = typeof SET_SAVED_SEARCH_RESULTS;

export const CLEAR_FILTER_RESULTS = 'CLEAR_FILTER_RESULTS';
export type CLEAR_FILTER_RESULTS = typeof CLEAR_FILTER_RESULTS;

export const REMOVE_SAVED_FILTER = 'REMOVE_SAVED_FILTER';
export type REMOVE_SAVED_FILTER = typeof REMOVE_SAVED_FILTER;

export const REMOVE_ALL_SAVED_FILTERS = 'REMOVE_ALL_SAVED_FILTERS';
export type REMOVE_ALL_SAVED_FILTERS = typeof REMOVE_ALL_SAVED_FILTERS;

export const SUBMIT_MESSAGE = 'SUBMIT_MESSAGE';
export type SUBMIT_MESSAGE = typeof SUBMIT_MESSAGE;

